# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.1.2"
  python_min: '3.11'

package:
  name: tinyio
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/t/tinyio/tinyio-${{ version }}.tar.gz
  sha256: f3f7350ac8a0d3eb35192d5c1a91f3c0cc1cfcadbb796c8a484efc8f2dcbca9d

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - hatchling
    - pip
    - python ${{ python_min }}.*
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - tinyio
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.13.*

about:
  summary: A tiny event loop for Python
  description: A tiny event loop for Python
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/patrick-kidger/tinyio

extra:
  recipe-maintainers:
    - davidbrochart
